#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-troveclient
Version  : 2.2.0
Release  : 21
URL      : http://tarballs.openstack.org/python-troveclient/python-troveclient-2.2.0.tar.gz
Source0  : http://tarballs.openstack.org/python-troveclient/python-troveclient-2.2.0.tar.gz
Summary  : Client library for OpenStack DBaaS API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-troveclient-bin
Requires: python-troveclient-python
BuildRequires : Babel-python
BuildRequires : Jinja2
BuildRequires : Sphinx-python
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : futures-python
BuildRequires : hacking
BuildRequires : httplib2
BuildRequires : keystoneauth1-python
BuildRequires : msgpack-python-python
BuildRequires : oslo.config
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-keystoneclient-python
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python-swiftclient-python
BuildRequires : python3-dev
BuildRequires : requests-mock-python
BuildRequires : setuptools
BuildRequires : simplejson
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv

%description
Python bindings to the OpenStack Trove API
==========================================

%package bin
Summary: bin components for the python-troveclient package.
Group: Binaries

%description bin
bin components for the python-troveclient package.


%package python
Summary: python components for the python-troveclient package.
Group: Default
Requires: Babel-python
Requires: prettytable
Requires: python-keystoneclient-python
Requires: python-swiftclient-python
Requires: simplejson

%description python
python components for the python-troveclient package.


%prep
cd ..
%setup -q -n python-troveclient-2.2.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/trove

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
