#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : python-troveclient
Version  : 2.5.0
Release  : 27
URL      : http://tarballs.openstack.org/python-troveclient/python-troveclient-2.5.0.tar.gz
Source0  : http://tarballs.openstack.org/python-troveclient/python-troveclient-2.5.0.tar.gz
Source99 : http://tarballs.openstack.org/python-troveclient/python-troveclient-2.5.0.tar.gz.asc
Summary  : Client library for OpenStack DBaaS API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-troveclient-bin
Requires: python-troveclient-python
Requires: Babel
Requires: keystoneauth1
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: python-mistralclient
Requires: python-swiftclient
Requires: requests
Requires: simplejson
Requires: six
BuildRequires : Babel-python
BuildRequires : Sphinx-python
BuildRequires : configparser-python
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : futures-python
BuildRequires : hacking
BuildRequires : httplib2
BuildRequires : keystoneauth1-python
BuildRequires : msgpack-python-python
BuildRequires : oslo.config
BuildRequires : oslo.utils
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pyparsing-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-keystoneclient-python
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python-swiftclient-python
BuildRequires : python3-dev
BuildRequires : requests-mock-python
BuildRequires : setuptools
BuildRequires : simplejson
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv

%description
Python bindings to the OpenStack Trove API
==========================================

%package bin
Summary: bin components for the python-troveclient package.
Group: Binaries

%description bin
bin components for the python-troveclient package.


%package python
Summary: python components for the python-troveclient package.
Group: Default

%description python
python components for the python-troveclient package.


%prep
%setup -q -n python-troveclient-2.5.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489036787
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test || :
%install
export SOURCE_DATE_EPOCH=1489036787
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/trove

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
